version: '3'

networks:
    app-network:
        driver: bridge

services:
    app:
        build: .
        container_name: app-api
        #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=api
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis
    nginx:
        build: .docker/nginx
        container_name: api-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app
    db:
        build: ./.docker/mysql
        container_name: api-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=virtual_odonto
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: api-phpmyadmin
        restart: always
        tty: true
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - app-network
